from .nnAudio_model import BCResNet_nnAudio,BCResNet_exp_nnAudio,Linearmodel_nnAudio,Linearmodel_nnAudio_ASR
from .fastaudio_model import BCResNet_Fastaudio, Linearmodel_Fastaudio
from .X_vector_model import X_vector